apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: aiaaa
  description: Everything related to artists
  title: aiaaa
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: user:guest
