apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "pm-api"
  annotations:
    jenkins.io/job-full-name: 'PM'
    gitlab.com/project-slug: 'gitlab/process-mining-api'
    backstage.io/kubernetes-namespace: 'backstage'
    backstage.io/kubernetes-id: 'hello-minikube'
    backstage.io/kubernetes-label-selector: 'app=hello-minikube'
spec:
  type: service
  system: process-mining
  owner: user:guest
  lifecycle: experimental

